- name: Install Apache2 Server
  yum:
    name: httpd
    state: present
  when: install_apache_flag

- name: Distribution
  debug: msg="{{ ansible_distribution }}"
- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"
- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"

- name: Combine conditions using ansible facts
  debug:
    var:
      - ansible_kernel
      - ansible_os_family
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_major_version == "20"