- name: Install Apache2 Server
  yum:
    name: httpd
    state: present
  when: install_apache_flag

- name: Distribution
  debug: msg="{{ ansible_os_family }}"
- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"
- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"

- name: Combine conditions using ansible facts
  debug:
      msg:
        - "ansible_os_family: {{ ansible_os_family }}"
        - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

# - name: Print all facts
#   debug:
#     var: ansible_facts

- name:
  command: cat $HOME/ansible/ansible-conditionals/test-file.txt
  register: test_file_content

- name: Use the file varibale in Conditional
  debug:
    msg: "test_file_content: {{test_file_content.stdout}}"

- name: Use the file varibale in Conditional
  debug:
    msg: "test_file_content: {{test_file_content.stdout}}"
  when: test_file_content.stdout.find('hi') != -1