- name: Install Apache2 Server
  yum:
    name: httpd
    state: present
  when: install_apache_flag

- name: Print OS and Kernel Version
  debug:
    var:
      - ansible_kernel
      - ansible_os_family

- name: Combine conditions using ansible facts
  debug:
    var:
      - ansible_kernel
      - ansible_os_family
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_major_version == "20"