- name: Install Apache2 Server
  yum:
    name: httpd
    state: present
  when: install_apache_flag

- name: Distribution
  debug: msg="{{ ansible_os_family }}"
- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"
- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"

- name: Combine conditions using ansible facts
  debug:
      msg:
        - "ansible_os_family: {{ ansible_os_family }}"
        - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"