---
- name: Install Python packages
  become: yes
  yum:
    name:
      - python3-pip
    update_cache: yes

- name: Create directory
  become: yes
  file:
    path: ./basic-http-server
    state: directory

- name: Install Apache2
  become: yes
  yum:
    name: httpd
    update_cache: yes
    state: latest