---
- name: Install Python packages
  become: yes
  yum:
    name:
      - python3-pip
    update_cache: yes
  register: python_installation_result

- name: Log python installation result
  debug:
    msg: "Python installation result: {{ python_installation_result }}"

- name: Create directory
  become: yes
  file:
    path: ./basic-http-server
    state: directory
  register: create_directory_result

- name: Log create directory
  debug:
    msg: "Create directory result: {{ create_directory_result }}"

- name: Install Apache2
  become: yes
  yum:
    name: httpd
    update_cache: yes
    state: latest
  register: install_apache2_result

- name: Log apache2 install
  debug:
    msg: "Install apache2 result: {{ install_apache2_result }}"

- name: index.html copy
  template: src=index.html dest=$HOME/index.html
  register: copy_index_result

- name: index.html copy result
  debug:
    msg: "index copy result: {{ copy_index_result }}"

- name: index.html copy
  template: src=updated.html dest=$HOME/index.html
  notify:
    - Restart Apache2
  register: restart_apache_result

- name: restart apache
  debug:
    msg: "restart_apache_result: {{ restart_apache_result }}"
