---
- name: Ansible Varibale playbook
  hosts: all
  roles:
    - ansible-varibales

  vars:
    main_playbook_varibale: "Hello, world in main playbook"
    is_enabled: true
    fruits_list:
      - apple
      - banana
      - orange
    fruits_dict:
      apple: 0.50
      banana: 0.51
      orange: 0.52



  tasks:
    - name: String vaibale from - main_playbook_varibale
      debug:
        var: main_playbook_varibale

    - name: boolean Variable
      debug:
        msg: "Varibale is_enabled is {{ is_enabled }}"
      when: is_enabled

    - name: List Variable
      debug:
        msg: "List varibale is {{ fruits_list }} and at index 0 we have {{ fruits_list[0] }}"

    - name: Dictionary Varibale
      debug:
        msg: "Fruit dictionary is {{ fruits_dict }} and apple price is {{ fruits_dict.apple }}"

    - name: Use Register Keyword
      command: echo "{{ fruits_dict['apple'] }}"
      register: apple_price_register_var
      debug:
        msg: "Data stored in Register variable {{ apple_price_register_var }} "
