---
- name: Ansible Varibale playbook
  hosts: all
  roles:
    - ansible-varibales

  vars:
    main_playbook_varibale: "Hello, world in main playbook"
    is_enabled: true

  tasks:
    - name: String vaibale from - main_playbook_varibale
      debug:
        var: main_playbook_varibale

    - name: boolean Variable
      debug:
        msg: "Varibale is true {{ is_enabled }}"
      when: is_enabled
      msg: "Varibale is true {{ is_enabled }}"