- name: Example for environment variable
  hosts: all
  become: yes
  roles:
    - env-var-role

  environment:
    EXAMPLE: "ENV1"
    MY_VAR2: "ENV2"

  tasks:
    - name: Environment variable at playbook level
      debug:
        msg: "{{ lookup('env', 'EXAMPLE') }}"

    - name: Task level environment variable
      environment:
        MY_TASK_ENV_VAR: "Task level env variable"
      command: "echo $MY_TASK_ENV_VAR"