---
- name: Ansible Varibale playbook
  hosts: all
  roles:
    - ansible-varibales

  vars:
    main_playbook_varibale: "Hello, world in main playbook"
    is_enabled: true
    fruits:
      - apple
      - banana
      - orange

  tasks:
    - name: String vaibale from - main_playbook_varibale
      debug:
        var: main_playbook_varibale

    - name: boolean Variable
      debug:
        msg: "Varibale is_enabled is {{ is_enabled }}"
      when: is_enabled

    - name: List Variable
      debug:
        msg: "List varibale is {{ fruits }}"