---
- name: Ansible Variable playbook
  hosts: all
  roles:
    - ansible-variables

  vars:
    # String
    main_playbook_variable: "Hello, world in main playbook"

    # Boolean
    is_enabled: true

    # List
    fruits_list:
      - apple
      - banana
      - orange

    # Dictionary
    fruits_dict:
      apple: 0.50
      banana: 0.51
      orange: 0.52

    # List of Dictionaries
    fruit_basket:
      - name: John
        fruits:
          - apple
          - orange
      - name: Jane
        fruits:
          - banana
          - apple

    # Get vars from file
    vars_files:
      - my-vars.yml

  tasks:
    - name: String variable from - main_playbook_variable
      debug:
        var: main_playbook_variable

    - name: Boolean Variable
      debug:
        msg: "Variable is_enabled is {{ is_enabled }}"
      when: is_enabled

    - name: List Variable
      debug:
        msg: "List variable is {{ fruits_list }} and at index 0 we have {{ fruits_list[0] }}"

    - name: Dictionary Variable
      debug:
        msg: "Fruit dictionary is {{ fruits_dict }} and apple price is {{ fruits_dict['apple'] }}"

    - name: Use Register Keyword
      command: echo "{{ fruits_dict['apple'] }}"
      register: apple_price_register_var

    - name: Display Register Variable
      debug:
        msg: "Data stored in Register variable {{ apple_price_register_var.stdout }}"

    - name: Get the value of apple from the nested variable
      debug:
        msg: "Price of apple in John's basket is {{ fruits_dict[fruit_basket[0].fruits[0]] }}"

    # Jinja 2 filters
    - name: Using Jinga 2 Filter on variables
      debug:
        var: fruits_dict.keys() | list | map('upper') | list

    - name: Getting var from file
      debug:
        msg: "{{ mars_from_my_vars_file }}"