---
- name: Ansible Variable playbook
  hosts: all
  roles:
    - ansible-variables

  vars:
    main_playbook_variable: "Hello, world in main playbook"
    is_enabled: true
    fruits_list:
      - apple
      - banana
      - orange
    fruits_dict:
      apple: 0.50
      banana: 0.51
      orange: 0.52

  tasks:
    - name: String variable from - main_playbook_variable
      debug:
        var: main_playbook_variable

    - name: Boolean Variable
      debug:
        msg: "Variable is_enabled is {{ is_enabled }}"
      when: is_enabled

    - name: List Variable
      debug:
        msg: "List variable is {{ fruits_list }} and at index 0 we have {{ fruits_list[0] }}"

    - name: Dictionary Variable
      debug:
        msg: "Fruit dictionary is {{ fruits_dict }} and apple price is {{ fruits_dict['apple'] }}"

    - name: Use Register Keyword
      command: echo "{{ fruits_dict['apple'] }}"
      register: apple_price_register_var
    
    - name: Display Register Variable
      debug:
        msg: "Data stored in Register variable {{ apple_price_register_var.stdout }}"